version: "3.8"
services:
  php:
    build:
      context: .
    volumes:
      - "./:/var/www/html"
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
